export type ApiError = { code: string; message: string; fieldErrors?: Record<string, string> };
export type IncomeKind = 'SALARY' | 'HONORARIA' | 'BONUS' | 'OTHER';
export type IncomeSourceRequest = {
  active: boolean;
  name: string;
  kind: IncomeKind;
  amount: number;
  inputMode: 'GROSS' | 'NET';
  frequency: 'MONTHLY' | 'ANNUAL' | 'ONE_TIME';
  months: number;
  taxable: boolean;
  withholdingRate: number;
  afpName: string;
  afpCommissionRate: number | null;
  healthSystem: 'FONASA' | 'ISAPRE' | 'NONE';
  healthPlanAmount: number;
  contractType: 'INDEFINITE' | 'FIXED';
  apvRegime: 'NONE' | 'A' | 'B';
  apvPaymentMethod: 'PAYROLL' | 'DIRECT';
  apvMonthly: number;
  notes: string;
  taxYear: number;
};
export type IncomeSourceResponse = IncomeSourceRequest & { id: number };
export function isApiError(value: unknown): value is ApiError;
export function incomeSourceRequest(value: Partial<IncomeSourceRequest>): IncomeSourceRequest;
export function incomeSourceResponse(value: unknown): IncomeSourceResponse;
export type WithholdingMode = 'WITHHELD_BY_RECIPIENT' | 'PPM_PAID_BY_ISSUER' | 'NO_WITHHOLDING';
export type FeeReceiptRequest = {
  taxYear: number; issueDate: string; folio: string | null; clientName: string; clientTaxId: string | null; description: string | null;
  amountInputType: 'GROSS' | 'NET'; grossAmount: number; netAmount: number; withholdingMode: WithholdingMode; withholdingRate: number;
  withheldAmount: number; ppmPaidAmount: number; taxable: boolean; status: 'ACTIVE' | 'CANCELLED'; paymentStatus: 'PENDING' | 'PAID';
  paymentDate: string | null; notes: string | null;
};
export type FeeReceiptResponse = FeeReceiptRequest & { id?: string; createdAt?: string; updatedAt?: string };
export type FeeReceiptFilters = { taxYear?: number | string; clientName?: string; status?: string; paymentStatus?: string; withholdingMode?: string };
export type FeeExpenseSettingsRequest = { taxYear: number; expenseMode: 'PRESUMED' | 'ACTUAL'; actualAnnualExpenses: number; notes: string | null };
export type FeeExpenseSettingsResponse = FeeExpenseSettingsRequest & { id?: string; createdAt?: string; updatedAt?: string };
export function feeReceiptRequest(value?: Partial<FeeReceiptRequest>): FeeReceiptRequest;
export function feeReceiptResponse(value?: Partial<FeeReceiptResponse>): FeeReceiptResponse;
export function feeReceiptFilters(value?: Partial<FeeReceiptFilters>): FeeReceiptFilters;
export function feeExpenseSettingsRequest(value?: Partial<FeeExpenseSettingsRequest>): FeeExpenseSettingsRequest;
export function feeExpenseSettingsResponse(value?: Partial<FeeExpenseSettingsResponse>): FeeExpenseSettingsResponse;
export type MortgagePurpose = 'PURCHASE' | 'CONSTRUCTION' | 'REFINANCING_ELIGIBLE_LOAN';
export type OwnershipType = 'SOLE_OWNER' | 'CO_OWNERSHIP' | 'SPOUSAL_COMMUNITY';
export type MortgageLoanRequest = {
  taxYear: number; institutionName: string; institutionTaxId: string | null; operationNumber: string | null; propertyAlias: string;
  propertyAddress: string | null; propertyRole: string | null; purpose: MortgagePurpose; ownershipType: OwnershipType; ownershipPercentage: number;
  isDesignatedBeneficiary: boolean; originalPrincipal: number | null; outstandingPrincipal: number | null; monthlyPayment: number | null;
  annualInterestPaid: number; annualPrincipalPaid: number | null; annualInsurancePaid: number | null; annualOtherCharges: number | null;
  certificateReference: string | null; certificateDate: string | null; eligibleForArticle55Bis: boolean; notes: string | null;
};
export type MortgageLoanResponse = MortgageLoanRequest & { id?: string; createdAt?: string; updatedAt?: string };
export type MortgageLoanFilters = { taxYear?: number | string; institutionName?: string; propertyAlias?: string };
export type MortgageAnnualRecordRequest = {
  taxYear: number; interestPaid: number; principalPaid: number | null; insurancePaid: number | null; otherCharges: number | null;
  certificateReference: string | null; certificateDate: string | null; notes: string | null;
};
export type MortgageAnnualRecordResponse = MortgageAnnualRecordRequest & { id?: string; mortgageLoanId?: string; createdAt?: string; updatedAt?: string };
export type MortgageAnnualRecordFilters = { taxYear?: number | string };
export function mortgageLoanRequest(value?: Partial<MortgageLoanRequest>): MortgageLoanRequest;
export function mortgageLoanResponse(value?: Partial<MortgageLoanResponse>): MortgageLoanResponse;
export function mortgageLoanFilters(value?: Partial<MortgageLoanFilters>): MortgageLoanFilters;
export function mortgageAnnualRecordRequest(value?: Partial<MortgageAnnualRecordRequest>): MortgageAnnualRecordRequest;
export function mortgageAnnualRecordResponse(value?: Partial<MortgageAnnualRecordResponse>): MortgageAnnualRecordResponse;
export function mortgageAnnualRecordFilters(value?: Partial<MortgageAnnualRecordFilters>): MortgageAnnualRecordFilters;
export type SettingsRequest = Record<string, string | number | boolean> & { year: number };
export type SettingsResponse = SettingsRequest & { ufValue: number; utmValue: number };
export type ReferenceResponse = { id: number; authority: string; title: string; url: string; appliesTo: string };
export type BootstrapResponse<S = unknown> = { settings: SettingsResponse; sources: S[]; references: ReferenceResponse[] };
export function settingsRequest(value?: Partial<SettingsRequest>): SettingsRequest;
export function settingsResponse(value?: Partial<SettingsResponse>): SettingsResponse;
export function bootstrapResponse<S = unknown>(value?: Partial<BootstrapResponse<S>>): BootstrapResponse<S>;
export function yearsResponse(value?: unknown): number[];
export function referenceResponse(value?: Partial<ReferenceResponse>): ReferenceResponse;
export type TaxParameterResponse = { ruleKey: string; value: number | string | boolean | null; type: string; description: string | null; updatedAt?: string };
export type TaxParametersRequest = { taxYear: number; values: Record<string, number | string | boolean | null> };
export type TaxParametersFilters = { taxYear?: number };
export type TaxRuleSourceRequest = { id?: string; ruleKey: string; taxYear: number; institution: string; title: string; sourceUrl: string; retrievedAt: string; notes: string | null };
export type TaxRuleSourceResponse = TaxRuleSourceRequest;
export type TaxRuleSourceFilters = { ruleKey?: string; taxYear?: number };
export function taxParameterResponse(value?: Partial<TaxParameterResponse>): TaxParameterResponse;
export function taxParametersRequest(value?: Partial<TaxParametersRequest>): TaxParametersRequest;
export function taxParametersFilters(value?: Partial<TaxParametersFilters>): TaxParametersFilters;
export function taxRuleSourceRequest(value?: Partial<TaxRuleSourceRequest>): TaxRuleSourceRequest;
export function taxRuleSourceResponse(value?: Partial<TaxRuleSourceResponse>): TaxRuleSourceResponse;
export function taxRuleSourceFilters(value?: Partial<TaxRuleSourceFilters>): TaxRuleSourceFilters;
export type SnapshotRequest = { name: string; payload: Record<string, unknown> };
export type SnapshotResponse = { id: number; result: unknown };
export type ScenarioResponse = { key: string; label: string; result?: unknown; liquidityCommitted: number; accumulatedPensionSaving: number; diff: number };
export type ExecutionLogRequest = { kind: 'SYNC' | 'ASYNC'; operation: string; status: 'OK' | 'ERROR'; message: string | null; auditMessage: string | null; durationMs: number };
export type ExecutionLogResponse = ExecutionLogRequest & { id: number; createdAt: string };
export type ExecutionLogFilters = { kind?: string; status?: string; operation?: string; q?: string; page?: number; pageSize?: number };
export type ExecutionLogPageResponse = { items: ExecutionLogResponse[]; total: number; page: number; pageSize: number };
export function snapshotRequest(value?: Partial<SnapshotRequest>): SnapshotRequest;
export function snapshotResponse(value?: Partial<SnapshotResponse>): SnapshotResponse;
export function scenarioResponse(value?: Partial<ScenarioResponse>): ScenarioResponse;
export function scenariosResponse(value?: unknown): ScenarioResponse[];
export function executionLogRequest(value?: Partial<ExecutionLogRequest>): ExecutionLogRequest;
export function executionLogResponse(value?: Partial<ExecutionLogResponse>): ExecutionLogResponse;
export function executionLogFilters(value?: Partial<ExecutionLogFilters>): ExecutionLogFilters;
export function executionLogPageResponse(value?: Partial<ExecutionLogPageResponse>): ExecutionLogPageResponse;
export type ApiErrorResponse = { code: string; message: string; fieldErrors?: Record<string, string> };
export type Pagination = { page: number; pageSize: number; total: number };
export function apiErrorResponse(value?: Partial<ApiErrorResponse>): ApiErrorResponse;
export function pagination(value?: Partial<Pagination>): Pagination;
