export type ApiError = { code: string; message: string; fieldErrors?: Record<string, string> };
export type IncomeKind = 'SALARY' | 'HONORARIA' | 'BONUS' | 'OTHER';
export type IncomeSourceRequest = {
  active: boolean;
  name: string;
  kind: IncomeKind;
  amount: number;
  inputMode: 'GROSS' | 'NET';
  frequency: 'MONTHLY' | 'ANNUAL' | 'ONE_TIME';
  months: number;
  taxable: boolean;
  withholdingRate: number;
  afpName: string;
  afpCommissionRate: number | null;
  healthSystem: 'FONASA' | 'ISAPRE' | 'NONE';
  healthPlanAmount: number;
  contractType: 'INDEFINITE' | 'FIXED';
  apvRegime: 'NONE' | 'A' | 'B';
  apvPaymentMethod: 'PAYROLL' | 'DIRECT';
  apvMonthly: number;
  notes: string;
  taxYear: number;
};
export type IncomeSourceResponse = IncomeSourceRequest & { id: number };
export function isApiError(value: unknown): value is ApiError;
export function incomeSourceRequest(value: Partial<IncomeSourceRequest>): IncomeSourceRequest;
export function incomeSourceResponse(value: unknown): IncomeSourceResponse;
