export { createIncomeService } from './incomes/income-service.js';
export type { IncomeService } from './incomes/income-service.js';
export { createFeeReceiptService } from './fees/fee-receipt-service.js';
export type { FeeReceiptService } from './fees/fee-receipt-service.js';
export { computeFeeReceiptPreview, computeFeeSummary, filterFeeReceipts } from './fees/fee-coordination.js';
export type { FeeReceiptComputed, FeeSummary, FeeReceiptFilters, FeeReceiptSortBy, WithholdingMode, FeeReceiptPreviewInput, FeeSummaryReceipt } from './fees/fee-coordination.js';
export { createMortgageService } from './mortgages/mortgage-service.js';
export type { MortgageService } from './mortgages/mortgage-service.js';
export { sanitizeMortgageLoan, annualRecordsByLoan, findAnnualInterest, buildDividendSchedule } from './mortgages/mortgage-coordination.js';
export type { MortgageLoanInput, AnnualRecordLike, DividendSchedule, DividendScheduleInput } from './mortgages/mortgage-coordination.js';
export { createScenarioService } from './scenarios/scenario-service.js';
export type { ScenarioService } from './scenarios/scenario-service.js';
export { isRegimeA, isRegimeB, baselineAnnualTax, scenarioApvBenefit } from './scenarios/scenario-coordination.js';
export type { ScenarioLike, ScenarioTotalsLike } from './scenarios/scenario-coordination.js';
export { createSourceService } from './sources/source-service.js';
export type { SourceService } from './sources/source-service.js';
export { filterReferences, filterTaxRuleSources } from './sources/source-coordination.js';
export type { ReferenceLike, TaxRuleSourceLike } from './sources/source-coordination.js';
export { createExecutionLogService } from './logs/execution-log-service.js';
export type { ExecutionLogService } from './logs/execution-log-service.js';
export { createSettingsService } from './settings/settings-service.js';
export type { SettingsService } from './settings/settings-service.js';
